### ISSUE TITLE
Display only a certain amount of pictures per page

### ISSUE THREAD

**Issue by WeWin55** [mikelothar/show-all-images-in-a-folder-with-php#2]
Hi,

this is not an issue! Your app is amazing, thanks for sharing this!
Is there a way to set the amount of picutures showen per page?
For example:
exmaple.com/pictures&amount=10

Or that the script it self only display 10 in a row and adds a button to display 10 more.
Something like that would be awesome!

Thanks for reading, i hope you understand my thoughts:)

**Comment by dvdn** [comment]
Hi, I recently implemented pagination in my fork of this project.
[dvdn / release v1.5.0](https://github.com/dvdn/show-all-images-in-a-folder-with-php/releases/tag/v1.5.0)

**Comment by tennisfar** [comment]
Excellent.
