### ISSUE TITLE
XSS sanitization?

### ISSUE THREAD

**Issue by CeeJayBeenz** [mikelothar/show-all-images-in-a-folder-with-php#7]
I noticed that you could just put a piece of code as the name (on linux of course) and it would automatically execute. No tricks needed. Is there any simple sanitation that I could use? *like replace < and > with _*

**Comment by tennisfar** [comment]
I've tried to replicate this without luck. Renamed an image to `<?php phpinfo(); ?>.png`.

You could try to wrap the `$image` variable in `htmlspecialchars($image)`.
